// Hand-built HTML fragment renderers pushed over the live-quiz WebSocket
// (slice 11). Same pattern as src/lib/fragments.ts (server-owns-the-markup,
// no client templating), but every fragment here is wrapped for htmx-ext-ws's
// out-of-band swap (`hx-swap-oob="true"` on the #live-room container id) —
// see docs/ADR-live-transport.md for the full message-shape documentation.
import { t, type Locale } from "../i18n";
import { escapeHtml } from "./html";
import type { RoomState, PublicLiveQuestion, LiveQuestion, ScoreboardEntry, TeamScoreboardEntry } from "../core/domain/liveQuiz";
import { toPublicQuestion, teamScoreboard } from "../core/domain/liveQuiz";
import type { MultipleChoicePayload, TrueFalsePayload, TypeAnswerPayload } from "../core/domain/types";

// LiveQuestion's payload field is a distributed conditional type keyed on a
// generic default (LiveCardType, itself a union) rather than a true
// discriminated union, so `switch (question.type)` alone doesn't narrow
// `question.payload` for TS — same reason core/domain/liveQuiz.ts's
// isAnswerCorrect casts per-branch instead of relying on narrowing.
function correctAnswerDisplay(question: LiveQuestion, locale: Locale): string {
  switch (question.type) {
    case "multiple_choice": {
      const p = question.payload as MultipleChoicePayload;
      return p.options[p.correctIndex] ?? "";
    }
    case "true_false": {
      const p = question.payload as TrueFalsePayload;
      return p.isTrue ? t("live.room.question.trueLabel", locale) : t("live.room.question.falseLabel", locale);
    }
    case "type_answer": {
      const p = question.payload as TypeAnswerPayload;
      return p.acceptedAnswers[0] ?? "";
    }
  }
}

function scoreboardListHtml(entries: ScoreboardEntry[], locale: Locale): string {
  return `<ol class="stack" style="list-style:decimal;padding-left:1.5em">${entries
    .map((e) => `<li>${escapeHtml(e.displayName)} — <strong>${escapeHtml(t("live.room.scoreboard.points", locale, { score: e.score }))}</strong></li>`)
    .join("")}</ol>`;
}

// --- Teams (slice 12) ---------------------------------------------------
// Team ids are plain positional slugs ("team-1", "team-2", ...) generated by
// core/domain/liveQuiz.ts's configureTeams — never a translated string (the
// domain layer stays locale-free, see that function's header comment). This
// is the one place a team id becomes a human-facing label, via i18n like
// every other UI string in this app.
function teamLabel(teamId: string, locale: Locale): string {
  const number = Number.parseInt(teamId.replace(/^team-/, ""), 10) || 0;
  return t("live.teams.teamLabel", locale, { number });
}

function teamScoreboardListHtml(entries: TeamScoreboardEntry[], locale: Locale): string {
  return `<ol class="stack" style="list-style:decimal;padding-left:1.5em">${entries
    .map(
      (e) =>
        `<li>${escapeHtml(teamLabel(e.teamId, locale))} — <strong>${escapeHtml(
          t("live.teams.leaderboard.points", locale, { score: e.score, count: e.playerCount }),
        )}</strong></li>`,
    )
    .join("")}</ol>`;
}

/** Host-only team-setup controls + a read-only view of current team assignments, shown in the lobby. */
function teamsLobbySectionHtml(room: RoomState, locale: Locale, isHost: boolean): string {
  const hostForm = isHost
    ? `<form ws-send class="row">
        <input type="hidden" name="type" value="configureTeams"/>
        <label>${escapeHtml(t("live.teams.countLabel", locale))}
          <input type="number" name="teamCount" min="1" step="1" value="${room.teamIds.length || 2}" required/>
        </label>
        <button type="submit" class="btn-secondary">${escapeHtml(t("live.teams.setButton", locale))}</button>
      </form>`
    : "";

  if (room.teamIds.length === 0 && !isHost) return "";

  // Per-player row: read-only for everyone; the host additionally gets a
  // team-select + move button so an auto-split result can be manually
  // overridden (assignLiveTeam/assignPlayerTeam) without re-shuffling the
  // whole room via configureTeams. Only rendered once teams exist — before
  // that there's nothing to reassign into.
  function playerRow(player: { userId: string; displayName: string; teamId: string | null }): string {
    if (!isHost || room.teamIds.length === 0) {
      return `<li>${escapeHtml(player.displayName)}</li>`;
    }
    const options = [
      `<option value="" ${player.teamId === null ? "selected" : ""}>${escapeHtml(t("live.teams.unassigned", locale))}</option>`,
      ...room.teamIds.map(
        (teamId) => `<option value="${escapeHtml(teamId)}" ${player.teamId === teamId ? "selected" : ""}>${escapeHtml(teamLabel(teamId, locale))}</option>`,
      ),
    ].join("");
    return `<li class="row">
      <form ws-send class="row" style="gap:var(--space-2)">
        <input type="hidden" name="type" value="assignTeam"/>
        <input type="hidden" name="userId" value="${escapeHtml(player.userId)}"/>
        <span>${escapeHtml(player.displayName)}</span>
        <select name="teamId">${options}</select>
        <button type="submit" class="btn-secondary">${escapeHtml(t("live.teams.moveButton", locale))}</button>
      </form>
    </li>`;
  }

  const allPlayers = Object.values(room.players);
  const rosterByTeam = room.teamIds.length
    ? `<ul class="stack">${room.teamIds
        .map((teamId) => {
          const members = allPlayers.filter((p) => p.teamId === teamId);
          return `<li><strong>${escapeHtml(teamLabel(teamId, locale))}</strong> (${escapeHtml(
            t("live.teams.playerCount", locale, { count: members.length }),
          )})<ul class="stack">${members.map(playerRow).join("")}</ul></li>`;
        })
        .join("")}
        ${(() => {
          const unassigned = allPlayers.filter((p) => p.teamId === null);
          return unassigned.length
            ? `<li><strong>${escapeHtml(t("live.teams.unassigned", locale))}</strong> (${escapeHtml(
                t("live.teams.playerCount", locale, { count: unassigned.length }),
              )})<ul class="stack">${unassigned.map(playerRow).join("")}</ul></li>`
            : "";
        })()}
      </ul>`
    : "";

  return `<section class="stack"><h3>${escapeHtml(t("live.teams.title", locale))}</h3>${hostForm}${rosterByTeam}</section>`;
}

/** Wraps inner markup for an out-of-band swap targeting the #live-room container. */
function oob(inner: string): string {
  return `<div id="live-room" hx-swap-oob="true" class="stack">${inner}</div>`;
}

export function renderLobbyFragment(opts: { room: RoomState; locale: Locale; isHost: boolean }): string {
  const { room, locale, isHost } = opts;
  const playerCount = Object.keys(room.players).length;
  const startButton = isHost
    ? `<form ws-send><input type="hidden" name="type" value="advance"/><button type="submit" class="btn-primary">${escapeHtml(t("live.room.lobby.startButton", locale))}</button></form>`
    : "";
  return oob(
    `<h2>${escapeHtml(t("live.room.title", locale))}</h2>
     <p>${escapeHtml(t("live.room.code", locale, { code: room.code }))}</p>
     <p><small>${escapeHtml(t("live.room.shareHint", locale))}</small></p>
     <p>${escapeHtml(t("live.room.lobby.waiting", locale))}</p>
     <p>${escapeHtml(t("live.room.lobby.playerCount", locale, { count: playerCount }))}</p>
     ${teamsLobbySectionHtml(room, locale, isHost)}
     ${startButton}`,
  );
}

export function renderQuestionFragment(opts: {
  room: RoomState;
  question: LiveQuestion;
  index: number;
  total: number;
  locale: Locale;
  isHost: boolean;
}): string {
  const { question, index, total, locale, isHost } = opts;
  const pub: PublicLiveQuestion = toPublicQuestion(question);

  let answerForm: string;
  if (pub.type === "multiple_choice") {
    answerForm = `<form ws-send class="stack">
      <input type="hidden" name="type" value="answer"/>
      <input type="hidden" name="cardId" value="${escapeHtml(pub.cardId)}"/>
      <p>${escapeHtml(pub.question)}</p>
      ${pub.options
        .map(
          (opt, i) =>
            `<label class="row"><input type="radio" name="rawAnswer" value="${i}" required/> ${escapeHtml(opt)}</label>`,
        )
        .join("")}
      <button type="submit" class="btn-primary">${escapeHtml(t("live.room.question.submit", locale))}</button>
    </form>`;
  } else if (pub.type === "true_false") {
    answerForm = `<form ws-send class="stack">
      <input type="hidden" name="type" value="answer"/>
      <input type="hidden" name="cardId" value="${escapeHtml(pub.cardId)}"/>
      <p>${escapeHtml(pub.statement)}</p>
      <label class="row"><input type="radio" name="rawAnswer" value="true" required/> ${escapeHtml(t("live.room.question.trueLabel", locale))}</label>
      <label class="row"><input type="radio" name="rawAnswer" value="false" required/> ${escapeHtml(t("live.room.question.falseLabel", locale))}</label>
      <button type="submit" class="btn-primary">${escapeHtml(t("live.room.question.submit", locale))}</button>
    </form>`;
  } else {
    answerForm = `<form ws-send class="stack">
      <input type="hidden" name="type" value="answer"/>
      <input type="hidden" name="cardId" value="${escapeHtml(pub.cardId)}"/>
      <p>${escapeHtml(pub.prompt)}</p>
      <input type="text" name="rawAnswer" placeholder="${escapeHtml(t("live.room.question.typeAnswerPlaceholder", locale))}" required/>
      <button type="submit" class="btn-primary">${escapeHtml(t("live.room.question.submit", locale))}</button>
    </form>`;
  }

  const hostControls = isHost
    ? `<form ws-send><input type="hidden" name="type" value="advance"/><button type="submit" class="btn-secondary">${escapeHtml(t("live.room.reveal.nextButton", locale))}</button></form>`
    : "";

  return oob(
    `<h2>${escapeHtml(t("live.room.question.number", locale, { current: index + 1, total }))}</h2>
     ${answerForm}
     <p id="live-answer-status" aria-live="polite"></p>
     ${hostControls}`,
  );
}

/** Sent privately (unicast) to the socket that just submitted an answer — see live-server.ts. */
export function renderAnswerAckFragment(opts: { correct: boolean; points: number; locale: Locale }): string {
  const { correct, points, locale } = opts;
  return `<p id="live-answer-status" hx-swap-oob="true" aria-live="polite">${escapeHtml(t("live.room.question.answered", locale))} ${
    correct ? `(${escapeHtml(t("live.room.reveal.correct", locale))} +${points})` : ""
  }</p>`;
}

export function renderRevealFragment(opts: { room: RoomState; question: LiveQuestion; locale: Locale; isHost: boolean }): string {
  const { room, question, locale, isHost } = opts;
  const board = Object.values(room.players)
    .map((p) => ({ userId: p.userId, displayName: p.displayName, score: p.score }))
    .sort((a, b) => b.score - a.score || a.displayName.localeCompare(b.displayName));

  const hostControls = isHost
    ? `<form ws-send><input type="hidden" name="type" value="advance"/><button type="submit" class="btn-primary">${escapeHtml(t("live.room.reveal.nextButton", locale))}</button></form>`
    : "";

  const teamBoard = room.teamIds.length
    ? `<h3>${escapeHtml(t("live.teams.leaderboard.title", locale))}</h3>${teamScoreboardListHtml(teamScoreboard(room), locale)}`
    : "";

  return oob(
    `<h2>${escapeHtml(t("live.room.reveal.title", locale))}</h2>
     <p><strong>${escapeHtml(correctAnswerDisplay(question, locale))}</strong></p>
     <h3>${escapeHtml(t("live.room.scoreboard.title", locale))}</h3>
     ${scoreboardListHtml(board, locale)}
     ${teamBoard}
     ${hostControls}`,
  );
}

export function renderFinishedFragment(opts: { entries: ScoreboardEntry[]; teamEntries?: TeamScoreboardEntry[]; locale: Locale }): string {
  const { entries, teamEntries, locale } = opts;
  const teamBoard = teamEntries && teamEntries.length
    ? `<h3>${escapeHtml(t("live.teams.leaderboard.title", locale))}</h3>${teamScoreboardListHtml(teamEntries, locale)}`
    : "";
  return oob(
    `<h2>${escapeHtml(t("live.room.finished.title", locale))}</h2>
     <h3>${escapeHtml(t("live.room.finished.podium", locale))}</h3>
     ${scoreboardListHtml(entries, locale)}
     ${teamBoard}`,
  );
}

export function renderUnknownRoomFragment(locale: Locale): string {
  return oob(`<p role="alert">${escapeHtml(t("live.room.errorUnknownRoom", locale))}</p>`);
}
